### ISSUE TITLE
Issue with xml data?

### ISSUE THREAD

**Issue by mrpg99** [xmltv-se/xmltv.se#14]
Hi,

I am not sure if its my tv backend thats at fault, or if there is an issue with the xml data i download?

I basically get this error message at the end of the xml data download 

/usr/bin/tv_grab_se_xmltvse: htsmsg_xml_deserialize error Expected '=' in attribute parsing
/usr/bin/tv_grab_se_xmltvse: grab returned no data

Many thanks for any input!

Best Regards
Patric

**Comment by jnylen** [comment]
Hi,
Never heard of tv_grab_se_xmltvse before.
Try to use the official tools such as tv_grab_se_tvzon or tv_grab_eu_dotmedia.

**Comment by mrpg99** [comment]
Hi,

Many thanks for the reply, i think the grabber came with tvheadend , i get no error messages when i now use the tv_grab_se_tvzon grabber that came with the xmltv package!

So thank you!

**Comment by mrpg99** [comment]
got this error again, and just for my info and to help others, delete your xmltv cache directory, usually located in /home/user/.xmltv/cache
