### ISSUE TITLE
AXESS TV is shifted one hour into the future

### ISSUE THREAD

**Issue by Jalle19** [xmltv-se/xmltv.se#15]
From the XMLTV data:

```
<programme start="20160127200000 +0100" stop="20160127204800 +0100" channel="axess.se">
    <title lang="sv">Vår genetiska kod</title>
    ...
</programme>
```

From http://axess.se/tv/Default.aspx:

`19.00 Vår genetiska kod - Del 1 av 2: Livets bok`

This makes it impossible to schedule timers using the XMLTV data (which is all I've got).

**Comment by jnylen** [comment]
Checking on it later today.

**Comment by Jalle19** [comment]
Thanks

**Comment by jnylen** [comment]
Should be fixed by tomorrow. Please comment if it doesn't.
Also, sorry for the slow fix.

**Comment by Jalle19** [comment]
Thanks, I'll let you know if it works in a few days!

**Comment by jnylen** [comment]
Fixed today. Thanks for reporting.
