### ISSUE TITLE
Incomplete schedules

### ISSUE THREAD

**Issue by wiborn** [xmltv-se/xmltv.se#16]
There seems to be an issue with some incomplete schedules for some channels, tv6.se today (2016-01-29) for example. It only contains 14 shows which is not correct.﻿

**Comment by jnylen** [comment]
Forced an update. If it still doesn't look correct tomorrow i'll look into it further.
Sorry for the slow update.

**Comment by wiborn** [comment]
No worries! Thanx for the help!

**Comment by jnylen** [comment]
Still looking into this. Can't figure out the problem. Sorry for the slow response.

**Comment by jnylen** [comment]
@wiborn: Could you check which channel this occurs on this month? And i'll check into it. I couldn't find any Viasat channel with that issue.

**Comment by jnylen** [comment]
No response in 16 days, closing this,

**Comment by jnylen** [comment]
A new issue can be found on #23 and the bug has been found. Look at the issue for newer details.
