### ISSUE TITLE
1326: parser error : Couldn't find end of Start Tag 

### ISSUE THREAD

**Issue by mrpg99** [xmltv-se/xmltv.se#17]
Hi,

I posted this on the xmltv.se earlier, but i cannot seem to add replies to that post anymore, so posting the issue here 

When i try and grab epg data using xmltv , i get the following 

hts@mediapc:/home/mrpg$ /usr/bin/tv_grab_se_tvzon 
:1326: parser error : Couldn't find end of Start Tag display- line 1326
    <display-
             ^
:1326: parser error : Premature end of data in tag channel line 1325
    <display-
             ^
:1326: parser error : Premature end of data in tag tv line 2
    <display-
             ^
I am unsure how this works, as there is only 481 lines in the grabber script, anyway i posted it here 

http://paste.ubuntu.com/14730846/

still getting the same error today, and i have no epg data left.

Best Regards
Patric

**Comment by jnylen** [comment]
Hi,
Yeah the google + groups are only for discussion now. Errors etc should be posted here so I can actually keep track of them.

Could you try to do a reconfigure (run tv_grab_se_tvzon --configure).

As http://combined.xmltv.se/ run tv_grab_se_tvzon and it doesn't provide any errors.

Also, try to install from source instead if the other things doesn't work. 
Git repo here: https://github.com/knowledgejunkie/XMLTV (it's git tracker of their cvs)

**Comment by mrpg99** [comment]
Hi,

Many thanks for the reply , i tried reconfiguring earlier, but did not help.

Also did install xmltv from source.

But re-configuring the grabber again now, gave me an idea, i deleted the cache directory, and it then started working again!

So many thanks for your help!

Br
Patric

**Comment by jnylen** [comment]
Nice it works again! ;)
