### ISSUE TITLE
All MTV Channel schedules are one hour off in Norway

### ISSUE THREAD

**Issue by pmespedal** [xmltv-se/xmltv.se#18]
All MTV Channel schedules are one hour off in Norway. May that be corrected?

Thanks in advance.

**Comment by jnylen** [comment]
Looking into it.

**Comment by jnylen** [comment]
MTV NO and Nick. NO looks ok now (even though its a few minutes off, these are the correct times reported by their API).

Could you confirm they look ok?

**Comment by pmespedal** [comment]
Hi,

 

The ones I’m receiving/am able to check are:

1.       NickJr.: Correct. XML data refkects actual broadcast

2.       MTC Live HD: XML data still seems to be 1 hour behind actual broadcast

3.       MTV Dance: XML data still seems to be 1 hour behind actual broadcast

**Comment by jnylen** [comment]
Hi,
Yeah MTV Live HD and MTV Dance uses a different importer. I'll look into it.

**Comment by jnylen** [comment]
Fixed tomorrow. Timezone was set to Europe/London (GMT).

**Comment by pmespedal** [comment]
Thank you!
