### ISSUE TITLE
Additional german channels

### ISSUE THREAD

**Issue by znirp** [xmltv-se/xmltv.se#19]
- [ ] N24 / N24 HD
- [x] Sky Bundesliga 2 - 10 / Sky Bundesliga 2 - 10 HD
- [x] Sky Sport 3-11 / Sky Sport 3-11 HD
- [ ] Sport1 US HD
- [ ] Sport 1 US HD1
- [ ] SPORT1 / SPORT1 HD
- [ ] Sport1+HD

Thanks in advance.

**Comment by jnylen** [comment]
Sport1 channels won't be added. They won't allow us to host the schedules on non-german servers. Our servers are currently in France (being moved to Sweden in the upcoming months).
The Sky channels should be able to be added.

I have tried getting in contact with N24 but no response yet.

**Comment by znirp** [comment]
I could offer you an Apache VHost (+ FTP Account) on a German Server if you're interested.
Probably interesting for some other channels if they have similarly terms.

> The Sky channels should be able to be added.

How I could recognize when they will be available?

**Comment by jnylen** [comment]
> I could offer you an Apache VHost (+ FTP Account) on a German Server if you're interested.
Currently this isn't needed. I do sell the data to commercial projects. So I will be able to pay for a cheap server myself.

> Probably interesting for some other channels if they have similarly terms.
Only SPORT1 got this terms regarding I can't use the SPORT1 name outside of Germany.
RTL, ProSieben. etc. got terms of no Synopsis (due to VG Media).

> How I could recognize when they will be available?
I should be able to add these later today or tomorrow. I'll post on the G+ group when it's in.

**Comment by znirp** [comment]
Thanks.

**Comment by jnylen** [comment]
Check up with SPORT1:
They said another server in Germany doesn't change the fact they can't license out the name SPORT1 outside of Dachau (DE, CH, AT).

They wanted me to refer you to http://tv.sport1.de/programm/monatsprogramm/

**Comment by jnylen** [comment]
Data will be in tomorrow. Sky Sport Austria HD (we only had SD before) is also in.

**Comment by jnylen** [comment]
You can find N24 on the list on issue #9.

**Comment by jnylen** [comment]
Lost config for bundesliga. So reopened.

**Comment by jnylen** [comment]
Fixed.
