### ISSUE TITLE
VH1 Norway vh1.no XML data still seems to be 1 hour behind actual broadcast

### ISSUE THREAD

**Issue by pmespedal** [xmltv-se/xmltv.se#20]
VH1 Norway / vh1.no XML data still seems to be 1 hour behind actual broadcast. Perhaps timezone is set to GMT?

Thanks.

**Comment by pmespedal** [comment]
Sorry - probably lag in sync in my end. It's spot on now.

**Comment by pukko** [comment]
Don't know if I should raise a new ticket for this, but I'm trying out xmltv again, and it seems like the VH1 times are 2 hours off in Sweden (epg is 2 hours early).

In vh1.se_2016-10-02.xml we have 
<programme start="20161002040000 +0200" stop="20161002060000 +0200" channel="vh1.se">
<title lang="en">Rise And Shine With VH1</title>

Though this show starts 0600, not 0400, Swedish time
