### ISSUE TITLE
http://xmltv.xmltv.se/channels-Denmark.xml.gz not being updated

### ISSUE THREAD

**Issue by twister5800** [xmltv-se/xmltv.se#21]
Hi, 
Why aren't the xmltv.xmltv.se/channels-Denmark.xml.gz not being updated anymore?

Br. Martin

**Comment by jnylen** [comment]
The file only gets updated when an channel gets edited, removed or added.

**Comment by twister5800** [comment]
Okay?

I have always used this file in my DVB software for the guide with no issues.

Which file do I then have to use?

BR. Martin

Den 2. mar. 2016 kl. 13.59 skrev Joakim Nyl?n <notifications@github.com<mailto:notifications@github.com>>:


The file only gets updated when an channel gets edited, removed or added.

-

**Comment by jnylen** [comment]
Hi,
I don't know what you use. Maybe you mean one of these files:
http://combined.xmltv.se/

**Comment by twister5800** [comment]
Maybe, i have been using this all along:
http://xmltv.xmltv.se/channels-Denmark.xml.gz

But I will try for http://combined.xmltv.se/denmark.xml in stead :-)

Br. Martin
