### ISSUE TITLE
bbcworldnews.com is missing data

### ISSUE THREAD

**Issue by anders55j** [xmltv-se/xmltv.se#22]
There is no data at all for the moment

**Comment by jnylen** [comment]
Looking into it

**Comment by jnylen** [comment]
Servern can't reach the bbc server. Looking into a fix.

**Comment by jnylen** [comment]
My hosting provider's whole ip range is blocked. So it will take some time to fix. Looking into how to fix it the easiest way.

**Comment by jnylen** [comment]
Seems fixed now after the whole main server died and restored from an old backup.
