### ISSUE TITLE
tv6.se is missing data

### ISSUE THREAD

**Issue by anders55j** [xmltv-se/xmltv.se#23]
the first gap is between 20160312055900 and 20160312235500. Just looking at the file sizes there seems to be more gaps ahead

**Comment by jnylen** [comment]
Looking into it

**Comment by jnylen** [comment]
Found the bug. There was an programme that existed before the other programmes and made it jump everything between 05:35 - Cops and 23:55 - Family Guy.

Looking into a fix later today.

**Comment by jnylen** [comment]
Fixed in xmltv-se/nonametv#14

**Comment by jnylen** [comment]
Still issues. Looking into it.

**Comment by jnylen** [comment]
Fixed.
