### ISSUE TITLE
Missing German Channels in http://combined.xmltv.se/germany.xml

### ISSUE THREAD

**Issue by FrankenWhine** [xmltv-se/xmltv.se#24]
Hi,
I started using http://combined.xmltv.se/germany.xml for my DVBLink Server. Unfortunately the file does not include following channels, but xmltv files do exist.

bfs.daserste.de
br-alpha.daserste.de

Would it be possible to include them in the germany.xml file?

Would be great!

Thnaks!

**Comment by jnylen** [comment]
Hi,
Actually it is in the file. Might be on your side.

**Comment by FrankenWhine** [comment]
Thanks a lot!
Sorry, I now found them after knowing they have to be there.
