### ISSUE TITLE
Episode numbering error in tv3.se

### ISSUE THREAD

**Issue by styrsven** [xmltv-se/xmltv.se#26]
I have noted that every episode of the "the mentalist" in tv3.se at least from today and currently existing future programs are tagged with the same episode number and title, even though the description differs.

Either the episode and title is wrong or (less likely) the description should be identical.

**Comment by jnylen** [comment]
No issues in the files. Might be your application.

**Comment by styrsven** [comment]
Actually, after looking closer there seems to be a general problem with several series in the tv3.se files. The hd.tv3.se files looks much saner. The examples below are fetched from http://xmltv.xmltv.se/

An example: in tv3.se_2016-05-17.xml there are two episodes of "The Nanny".

One starting at 20160517053500 +0200 with subtitle "Pilot (a.k.a. The Nanny)",
description
" C.C.s far kommer på middag och trots C.C.s försök, så får Fran och Maxwell all uppmärksamhet. Pappan bjuder med Fran på Barbara Streisand-konsert och Fran får till och med träffa sångerskan backstage.",
and onscreen episode "Del 1 säsong 1".
The second starting at 20160517060000 +0200 with subtitle "Pilot (a.k.a. The Nanny)",
description
"Frannies val. Fran blir uppsökt av Danny, hennes gamla ex, som just har blivit singel efter ett långt förhållande. Fran och Danny börjar träffas igen, men när han friar till henne måste hon fatta ett svårt beslut. Ska hon gifta sig med Danny eller stanna hos familjen Sheffield?"
and onscreen episode "Del 1 säsong 1"

In hd.tv3.se_2016-05-17.xml, the times and descriptions are identical, but the subtitles and episodes corresponds to the description,
The first example has the subtitle "Ode to Barbara Joan (a.k.a. Daddy Dearest)" and onscreen episode "Del 20 säsong 1"
and the second has subtitle "Frannie's Choice" with onscreen episode "Del 21 säsong 1"

**Comment by jnylen** [comment]
That's weird. Because TV3 HD just copies the programmes from tv3.se and adds HDTV tag.

**Comment by styrsven** [comment]
The issue persists. Only 2016-06-06 was updated, both for tv3.se and hd.tv3.se
The tv3.se files seems to have been updated 2016-05-10
The hd.tv3.se files are mostly older. Note that from 2016-06-01 they are empty.

**Comment by jnylen** [comment]
Hi,
Found the issue. It put the season number as episode number. Fixed tomorrow.
