### ISSUE TITLE
ginx.tv

### ISSUE THREAD

**Issue by pukko** [xmltv-se/xmltv.se#27]
ginx.tv epg seems empty, is it something that could be fixed?

(keep up the great work!)

**Comment by jnylen** [comment]
Fixed. Issue for June though.

The channel files that the schedule is imported from is added manually and it hasn't been on my priority list to keep this one up2date as it has vanished from all swedish tv providers.

**Comment by pukko** [comment]
Actually, comhem decided to keep it.
