### ISSUE TITLE
Season and episode in local language?

### ISSUE THREAD

**Issue by znirp** [xmltv-se/xmltv.se#28]
Is there a change to add the season and episode title in local language or at least in englisch?

000d8b404599216108d3c446b8a7ba87:    <episode-num system="onscreen">Del 13 säsong 2011</episode-num>
000d8b404599216108d3c446b8a7ba87:    <episode-num system="onscreen">Del 13 säsong 2011</episode-num>
000d8b404599216108d3c446b8a7ba87:    <episode-num system="onscreen">Del 3 säsong 1</episode-num>
0018d5ae6d72df4976238b481cee10fe:    <episode-num system="onscreen">Del 12 säsong 2</episode-num>
0018d5ae6d72df4976238b481cee10fe:    <episode-num system="onscreen">Del 12 säsong 4</episode-num>

Thanks in advance.

**Comment by jnylen** [comment]
Which channels?

**Comment by znirp** [comment]
Attached you'll find all channels, which have the string "säsong" in its cache file:

13thstreet.de
animalplanet.discovery.de
animax.tv
atlantichd.sky.de
atlantic.sky.de
boomerangtv.de
cartoonnetwork.com
cartoonnetwork.de
comedycentral.de
crimehd.rtl.de
crime.rtl.de
discovery.de
disneychannel.de
dmax.discovery.de
emotions.sat1.de
fun.prosieben.de
hd.13thstreet.de
hd.discovery.de
hd.historytv.de
hd.historytv.se
hd.natgeo.de
hd.spiegel-geschichte.tv
hd.tnt-glitz.tv
hd.tnt-serie.de
hd.zdf.de
infokanal.zdf.de
jr.disneychannel.de
jr.nick.de
junior.tv
kultur.zdf.de
living.rtl.de
maxx.prosieben.de
motorvision.de
mtv.de
natgeo.de
neokika.zdfmobil.de
neo.zdf.de
nick.de
passion.de
rtl2.de
sat1.de
spiegel-geschichte.tv
super.rtl.de
tlc.discovery.de
tnt-serie.de
toons.nick.de
viva.tv
vox.de
wildhd.natgeo.de
wildhd.natgeo.se
wild.natgeo.de
wild.natgeo.se
xd.disneychannel.com
xd.disneychannel.de
zdf.de

**Comment by jnylen** [comment]
Our exporter only exports in a specific language. I'll try to fix it later on. It should default to the language the channel is in if that language doesn't exist it should go back to English.

Added an issue: xmltv-se/nonametv#107

**Comment by znirp** [comment]
Thanks

**Comment by jnylen** [comment]
You should be able to calculate the string by yourself though.

Just check the xmltv_ns and +1 on the season and episode numbers.

**Comment by znirp** [comment]
Maybe got an example? I have different values on xmltv_ns

    ```
<episode-num system="xmltv_ns">1 . 5 .</episode-num>
    <episode-num system="onscreen">Del 6 säsong 2</episode-num>

    <episode-num system="xmltv_ns">1 . 0 .</episode-num>
    <episode-num system="onscreen">Del 1 säsong 2</episode-num>
    <episode-num system="thetvdb.com">series/83682</episode-num>

    <episode-num system="xmltv_ns">0 . 9 .</episode-num>
    <episode-num system="onscreen">Del 10 säsong 1</episode-num>

    <episode-num system="xmltv_ns">. 2 .</episode-num>
    <episode-num system="onscreen">Del 3</episode-num>

```

**Comment by jnylen** [comment]
just run on <episode-num system="xmltv_ns">1 . 0 .</episode-num>
First digit is season with -1 and the middle digit is episode -1

<episode-num system="xmltv_ns">. 2 .</episode-num>
Has no season so only episode in the middle with -1.

So just grab those two and create your own onscreen.

**Comment by jnylen** [comment]
Hi again znirp,
I will be moving everything over to one language. English.
It wont have different language based on the schedule lang.

if you want another language you need to do it at your side.
