### ISSUE TITLE
Two well-known German services are missing.

### ISSUE THREAD

**Issue by Physikbuddha** [xmltv-se/xmltv.se#29]
Reference to #9 
Two of the nine German [regional public-broadcasting organizations](https://de.wikipedia.org/wiki/Landesrundfunkanstalt) are missing:
- [ ] BR (Bayerischer Rundfunk)
- [x] SR (Saarländischer Rundfunk)

They all are members of the main public service broadcaster ['Das Erste'](https://en.wikipedia.org/wiki/Das_Erste#Member_broadcasting_organizations). The other ones are already included in your list, so we should be able to get the data from the other two as well.
It would be nice to see them being added to the list.

**Comment by dekarl** [comment]
SR is a variant of SWR, just like SWR BW and SWR, see sr.swr.daserste.de

**Comment by Physikbuddha** [comment]
You're right, didn't know that.
This leaves my request single to BR.

**Comment by jnylen** [comment]
Looking into it.

**Comment by dekarl** [comment]
just looked at the press site.
BR is called BFS and is available as bfs.daserste.de
BR alpha (now ARD alpha) is available as br-alpha.daserste.de
