### ISSUE TITLE
VH1 Norway data 1 hour behind actual broadcast

### ISSUE THREAD

**Issue by pmespedal** [xmltv-se/xmltv.se#30]
VH1 Norway / vh1.no XML data seems to be 1 hour behind actual broadcast. Perhaps timezone is set to GMT? Also MTV Dance seems to be 1 hour off.

Thanks.

**Comment by jnylen** [comment]
Is VH1 Sweden correct?

**Comment by pmespedal** [comment]
I’m afraid I do not know as I have not got the listing in the xml I download, nor do I receive the SE channel (if that is a different one from the NO version).

**Comment by pmespedal** [comment]
Actually, Comedy Central is also one hour off. Being a part of the same broadcasting group, this might be related?

**Comment by jnylen** [comment]
Sorry for the non-answer. Is it still the same issue? Norway and Sweden should be in the same timezone with the same data.

**Comment by pmespedal** [comment]
Thanks for the answer – Finally ;)

 

Actually, there seems to be a bit of a “mess” with all the Viacom channels. See attached screenshot, Though; You may compare with http://north.viacom.com/no/vh1/schedule/ - Which seems to be one hour off from the actual CEsT broadcast too…

**Comment by jnylen** [comment]
They changed the source of the data for whole VH1 Europe. Should be fine tomorrow.

**Comment by pukko** [comment]
Don't know if I should raise a new ticket for this, but I'm trying out xmltv again, and it seems like the VH1 times are 2 hours off in Sweden (epg is 2 hours early).

In vh1.se_2016-10-02.xml we have 

Rise And Shine With VH1

Though this show starts 0600, not 0400, Swedish time

**Comment by jnylen** [comment]
Fixed, it didn't tell the database the time converted was UTC. Data tomorrow.
