### ISSUE TITLE
Swedish channels not getting new data

### ISSUE THREAD

**Issue by rogermartensson** [xmltv-se/xmltv.se#32]
It seems that atleast these channels does not get any new data:

- Kanal 5/HD
- kanal 9
- kanal 11
- Discovery HD
- Travel Channel
- BBC Brit HD

When looking at http://xmltv.xmltv.se I see lots of 0.1K-files. Haven't checked all but it looks kinda small.
When looking at: hd.kanal5.se_2016-06-30.xml
On 2016-06-11 18:56 I see this in the file.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv generator-info-name="Taiga XMLTV" generator-info-url="http://xmltv.se"></tv>
```

**Comment by jnylen** [comment]
Hi,
As I wrote on the Google+ group and its on xmltv.xmltv.se there is some channels missing data.
Most of those are fixed.
