### ISSUE TITLE
Finnish subtitle on Norwegian channels

### ISSUE THREAD

**Issue by tobbenb** [xmltv-se/xmltv.se#34]
I recently started getting finish subtitles in tvheadends EPG after running the xmltv grabber more channels had the same problem.
The channels I have noted is TV 2 Humor HD, Comedy Central N HD, Fox HD, TV 2 Zebra HD, TV3 HD, Viasat 4  HD.
Their might be more also as I just checked the channels I mostly use and only a couple of hours ahead.

I use the tv_grab_no_gfeed xmltv grabber.

I can add that I'm using this address for the grabber:
`http://xmltv.xmltv.se/channels-Norway.xml.gz`

**Comment by jnylen** [comment]
Can you link a day of data for a channel that have finnish subtitles?
They shouldnt have it.

**Comment by tobbenb** [comment]
Here is one `http://xmltv.xmltv.se/humor.tv2.no_2016-06-19.xml`
You can see it's Finish in the first show:
`<sub-title lang="no">Halaus on hyvä hinta</sub-title>`

It doesn't look like all shows have Finish language though.

**Comment by jnylen** [comment]
Found the issue. Fixed.

**Comment by tobbenb** [comment]
Thanks a lot.

**Comment by jnylen** [comment]
Btw, changing the augmenter for TV2 Humor to Tmdb so it will match better, if it works i'll change it on all of the TV2NO channels.

**Comment by tobbenb** [comment]
There are still issues with Finnish on some channels. Both FOX and TV3 have Finnish subtitle on at least the NCIS shows. TV2 Humor HD doesn't have subtitles anymore on most shows.
For FOX you can see Finnish in the first program here [http://xmltv.xmltv.se/foxtv.no_2016-07-03.xml](url)

**Comment by jnylen** [comment]
Looking into it.

**Comment by jnylen** [comment]
Fixed. It was data left behind from when it had the wrong language.
TV2 Humor had no subtitles due to it not having it for the norwegian title on TMDb. Moved to english language.
