### ISSUE TITLE
SVT2 guide data incorrect

### ISSUE THREAD

**Issue by TobbeJ** [xmltv-se/xmltv.se#38]
Hello.

guide data for SVT2 for example today's episode of mr robot is too short.
also following programs is also off by about 20 minutes or so.

guide data was refreshed after i noticed this but still same incorrect times.
start time was good but not end time.

**Comment by jnylen** [comment]
Hi,
Looks like SVT provider a too early start time for the programme after Mr Robot so the endtime of Mr Robot got cut short.

It's up2date now but too late.

Not a bug in our system. Just a tiny issue caused by SVT.
