### ISSUE TITLE
MTV live HD schedule is 1 hour behind actual broadcast 

### ISSUE THREAD

**Issue by pmespedal** [xmltv-se/xmltv.se#40]
Hi,

MTV Live HD schedule (hd.mtv.se from norway.xml) seems 1 hour behind actual broadcast. The rest of the Viacom schedules now seems correct. Thanks in advance for having a look.

**Comment by jnylen** [comment]
Can you check VH1 Classic if they match? They are on the same importer.

**Comment by pmespedal** [comment]
From and with today both MTV Live HD and VH1 Classic is spot on with the broadcast, so false alarm. Something has changed for the better. 

Thank you.

**Comment by jnylen** [comment]
To be honest, that's weird. I haven't touched anything.
Probably some spooky schedule files.
